### ISSUE TITLE
[help-needed]Can I pull remote files into an empty folder?

### ISSUE THREAD

**Issue by ZiyiFeng-SJSU** [mkloubert/vscode-deploy-reloaded#13] opened 2018-01-11 03:25 UTC
### Description

I am trying to pull remote directory to an empty folder, just as a SFTP does.

### Actual behavior
If I asked it to List Directory, it will show everything in the remote directory. However, when I asked it to pull, it would be:    
[vscode-deploy-reloaded]::[testing_student4] No files found!   

### Expected behavior

I was hoping it could pull all the files. 

### Steps to reproduce

{Please write here, including precondition and an example config, if possible}

#### Example config

```json
{
  "deploy.reloaded": {
    "packages": [
      {
        "name": "test",
        "description": "Package version 2.3.4",
        "exclude": [
          "tests/**",
          ".vscode/**",
          ".vscode",
          "node_modules/**",
          "app/bower_components/**",
        ],
        "files": [
          "**"
        ],
        // "removeOnChange": [
        //   "student4"
        // ],
        // "deployOnSave": [
        //   "student4"
        // ],
        "syncWhenOpen": "student4"
      }
    ],
    "targets": [
      {
        "type": "sftp",
        "name": "student4",
        "description": "A SFTP folder",
        "dir": "/XXXXXXX",
        "host": "XXXXXX",
        "user": "XXX",
        "privateKey": "XXXXXX",
      }
    ]
  }
}
```
### Your environment

- Operating system: Linux 17.10   
- Visual Studio Code version: 1.19.2   
- Extension version: 0.28.5

**Comment by ZiyiFeng-SJSU** [comment] 2018-01-14 01:54
Thank you for such immediate update!   
When I was testing it on the empty folder, it pulled all the folder down but no file, not even files in the parent folder. 
```
Pulling files from to '/home/XXX/Dropbox/testing_student4' ...
	Pulling file '/home/zfeng/src/student4/npm-debug.log' ... [ERROR: 'No such file']
	Pulling file '/home/zfeng/src/student4/.yo-rc.json' ... [ERROR: 'No such file']
[Done]
```

**Comment by mkloubert** [comment] 2018-01-14 11:13
@ZiyiFeng-SJSU 

Can you download these files via another SFTP client with the same settings / credentials?

**Comment by ZiyiFeng-SJSU** [comment] 2018-01-16 00:52
Yea. Even your SFTP client pulled perfectly fine when I have files of a leaf- folder pre-existed.    
```
Pulling file '/home/XXX/Dropbox/student4/list-page.html' from  '/ (student4)' ... [OK]
Pulling file '/home/XXX/Dropbox/student4/my-app.html' from  '/ (student4)' ... [OK]
Pulling file '/home/XXX/Dropbox/student4/my-icons.html' from  '/ (student4)' ... [OK]
```

**Comment by mkloubert** [comment] 2018-01-24 03:40
@ZiyiFeng-SJSU 

Sorry when I answer so late ... **the issue should be fixed with version 0.30.1 now.**

The problem was, if I tried to reproduce the issue on my local windows test server, I did not get the error.

After I had the time to install a real linux machine, a similar error was displayed in my output window.

**Comment by ZiyiFeng-SJSU** [comment] 2018-01-24 07:17
Np @mkloubert ! Thank you for keep everything updated!   
Right now on linux, it finally be able to pull files from the top level folder, it can also pull sub-folder, but it can't pull folder/files within sub-folder.    
```
Pulling files from to '/home/zoe/Dropbox/testing_student4' ...
	Pulling file '/.yo-rc.json' ... [OK]
        ...
	Pulling file '/.gitreview' ... [OK]
[Done]
```
Error message when trying to pull sub-folder: 
```
Pulling files from 'home/zfeng/src/student4/src' to '/home/zoe/Dropbox/testing_student4/src' ...
[ERROR: 'No such file']
```
I attached the picture to show the empty folder and the top-level files that were pulled:   
![image](https://user-images.githubusercontent.com/16110020/35319170-83b6eb8e-0093-11e8-887c-94faab598e7a.png)

**Comment by mkloubert** [comment] 2018-01-24 08:49
@ZiyiFeng-SJSU 

Thanks for the quick response!

**The issue should be fixed in version 0.30.2** now.

**Comment by ZiyiFeng-SJSU** [comment] 2018-01-25 07:30
Niiiiiice! Now it is pulling files!    
I am doing a test that asks it pulls more than ten thousands files in a node_modules folder see if it breaks =]     
It had an `EMFILE error:too many open files` once, I am seeing if I can reproduce it.

**Comment by ZiyiFeng-SJSU** [comment] 2018-01-26 23:06
Do you want me to open another issue with this error and close the current one?

**Comment by mkloubert** [comment] 2018-02-14 04:57
@ZiyiFeng-SJSU 

Unfortunately, I could not reproduce it.

If it happens again, you should open a new issue.

**Closed by mkloubert** 2018-02-14 04:57 UTC
Labels: enhancement, good first issue
